name: calculator
description: A simple calculator application for ExpidusOS
publish_to: 'none'
version: 0.1.1+1
homepage: https://expidusos.com
funding:
  - https://opencollective.com/expidusos

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.17+2
  libtokyo:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: f48d528ebfc22fe827fe9f2d1965be1d339ccfb7
      path: packages/libtokyo
  libtokyo_flutter:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: f48d528ebfc22fe827fe9f2d1965be1d339ccfb7
      path: packages/libtokyo_flutter
  markdown: ^7.1.1
  math_expressions: ^2.4.0
  package_info_plus: ^4.1.0
  provider: ^6.0.5
  pub_semver: ^2.1.4
  pubspec: ^2.3.0
  sentry_flutter: ^7.9.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14

dependency_overrides:
  win32: ^5.0.5
  libtokyo:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: f48d528ebfc22fe827fe9f2d1965be1d339ccfb7
      path: packages/libtokyo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/imgs/icon.webp
    - pubspec.yaml
    - .dart_tool/package_config.json
    - PRIVACY.md
