name: calculator
description: A simple calculator application for ExpidusOS
publish_to: 'none'
version: 1.0.0+1
homepage: https://expidusos.com
funding:
  - https://opencollective.com/expidusos

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.17+2
  expidus:
    git:
      url: https://github.com/ExpidusOS/libexpidus.git
      ref: d7e15fb66ca5a9b285cbe2eb301fa65a2a196b74
  markdown: ^7.1.1
  math_expressions: ^2.4.0
  package_info_plus: ^4.1.0
  provider: ^6.0.5
  pub_semver: ^2.1.4
  sentry_flutter: ^7.9.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  pubspec_parse: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/imgs/icon.webp
    - pubspec.yaml
    - .dart_tool/package_config.json
    - PRIVACY.md
